apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-legacy
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-legacy
  template:
    metadata:
      labels:
        app: wordpress-legacy
    spec:
      containers:
      - name: wordpress
        image: anna408/wordpress-legacy:0.1.0
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb.default.svc.cluster.local:3306
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: anna
        - name: WORDPRESS_DB_PASSWORD
          value: Nanachou17
